# Generated by Django 3.1.7 on 2021-03-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time_to_finish',
        ),
    ]
