# Generated by Django 3.1.7 on 2021-04-19 01:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210302_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
